//Inscription
POST localhost:8000/api/auth/register
Content-Type: application/json

{
  "username": "user",
  "email": "ally@contact.com",
  "password": "123456"
}

###

//activation du compte
POST localhost:8000/api/activate
Content-Type: application/json

{
  "code":"775386"
}

###
//authentification
POST localhost:8000/api/auth/connexion
Content-Type: application/json

{
  "email": "ally@contact.com",
  "password": "123456"
}

###
//Ajout budget
POST localhost:8000/api/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGx5QGNvbnRhY3QuY29tIiwibm9tIjoidXNlciIsImV4cCI6MTc1MTAwMDY3NH0.YsWlUYOMsst-RdZ1t6w6K7jQtUhdUjYuGJF8bZ6i-V0

{
  "motif": "Dépenses mensuelles",
  "month": "Juin",
  "description": "Budget pour Juin, couvrant la nourriture, transport, etc.",
  "amount": "200000",
  "userId": 352
}


###
//recuperation budgets
GET localhost:8000/api/budget
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGx5QGNvbnRhY3QuY29tIiwibm9tIjoidXNlciIsImV4cCI6MTc1MTAwMDY3NH0.YsWlUYOMsst-RdZ1t6w6K7jQtUhdUjYuGJF8bZ6i-V0

###
//Recuperation de budgets par Id
GET localhost:8000/api/budget/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGx5QGNvbnRhY3QuY29tIiwibm9tIjoidXNlciIsImV4cCI6MTc1MTAwMDY3NH0.YsWlUYOMsst-RdZ1t6w6K7jQtUhdUjYuGJF8bZ6i-V0
