POST localhost:8000/api/login
Content-Type: application/json

{
  "username": "user",
  "email": "ally@contact.com",
  "password": "123456"
}

###

POST localhost:8000/api/activate
Content-Type: application/json

{
  "code":"775386"
}

###

POST localhost:8000/api/connexion
Content-Type: application/json

{
  "email": "ally@contact.com",
  "password": "123456"
}